development:
  adapter: mysql
  database: harvesttarget_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql
  database: harvesttarget_development
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql
  database: harvesttarget_development
  encoding: utf8
  username: root
  password:
